"""create reader_subscription table

Revision ID: 840cfe9413e2
Revises: f0a121b6e399
Create Date: 2021-06-02 19:17:58.549939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840cfe9413e2'
down_revision = 'f0a121b6e399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reader_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription', sa.String(length=15), nullable=True),
    sa.Column('payment', sa.String(length=19), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reader_subscriptions')
    # ### end Alembic commands ###
